# minutemail-stripe-webhook Kubernetes deployment and ingress YAML

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minutemail-stripe-webhook
  labels:
    app: minutemail-stripe-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minutemail-stripe-webhook
  template:
    metadata:
      labels:
        app: minutemail-stripe-webhook
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: minutemail-stripe-webhook
          image: chrptvn/minutemail-stripe-webhook:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: "redis-master.minutemail.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"

---
apiVersion: v1
kind: Service
metadata:
  name: minutemail-stripe-webhook
spec:
  type: ClusterIP
  selector:
    app: minutemail-stripe-webhook
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minutemail-stripe-webhook
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - api.minutemail.co
      secretName: api-minutemail-tls

  rules:
    - host: api.minutemail.co
      http:
        paths:
          - path: /v1/stripe_webhook
            pathType: Prefix
            backend:
              service:
                name: minutemail-stripe-webhook
                port:
                  number: 8080
